// ? START COMPONENTS ---
import Topnav from "./components/Topnav";
// ! END COMPONENTS ---

// ? START FONTS ---
import { Nunito } from "next/font/google";
import { Poppins } from "next/font/google";

const nunito = Nunito({
  weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000'],
  subsets: ['latin']
});
const poppins = Poppins({
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin']
});
// ! END FONTS ---

// ? START STYLES ---
import "/public/globals.css";
// ! END STYLES ---

export const metadata = {
  title: "Tailwind",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="preload" href="./images/prog-bg.jpg" as="image" />
      <body className={poppins.className}>

        <Topnav />

        <main>
          {children}
        </main>
        
      </body>
    </html>
  );
}
